- name: /etc/limits.conf configurations
  community.general.pam_limits:
    domain: "{{ item.domain }}"
    limit_type: "{{ item.limit_type }}"
    limit_item: "{{ item.limit_item }}"
    value: "{{ item.value }}"
  with_items:
    - "{{ linux_ulimit_info }}"
  become: yes

